# secret-django.yaml
apiVersion: v1
kind: Secret
metadata:
  name: reverseip-app-secrets
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWplMXRtMzh1YXdAKWhzMnQmeHotbHgrK2YqZV9ubGVuNio9eCo9YV4xKXl2Mz12dTVw
  DEBUG: VHJ1ZQ==
  MONGODB_ENGINE: ZGpvbmdv
  MONGODB_NAME: cmV2ZXJzZWlw
  MONGODB_ENFORCE_SCHEMA: RmFsc2U=
  MONGODB_HOST: bW9uZ29kYitzcnY6Ly9kYXlvOkx1a2V3b3JtNTZAY2x1c3RlcjAuZmJqdHp6ay5tb25nb2RiLm5ldC9yZXZlcnNlaXA/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=
